CREATE DATABASE sistema;

CREATE TABLE usuario (
id INT PRIMARY KEY AUTO_INCREMENT, 
login VARCHAR (20) NOT NULL UNIQUE,
senha VARCHAR (20) NOT NULL,   
nome VARCHAR (50) NOT NULL,
cpf VARCHAR(11) NOT NULL UNIQUE,
email VARCHAR (30) NOT NULL UNIQUE,
rg VARCHAR (7) NOT NULL UNIQUE,
pai VARCHAR(50) NOT NULL,
mae VARCHAR (50)NOT NULL,
nascimento VARCHAR (10) NOT NULL

);

